//
//  Hemodynamic_Information.swift
//  Critical.X
//
//  Created by Jadie Barringer III on 2/3/19.
//  Copyright © 2019 Jadie Barringer III. All rights reserved.
//

import Foundation

enum ParameterDetails: String {
    
    case ArterialOxygenSaturation = """
    An SaO2 is determined by doing an Arterial Blood Gas (ABG). Values under 90% are considered low and require supplemental oxygen.
    \rPeripheral oxygen saturation (SpO2) is an estimation of the oxygen saturation level usually measured with a pulse oximeter.
    \rAny value < 60% is considered hypoxemic and indicate a need for supplemental oxygen.
    """
    
    case MixedVenousSaturation = """
    \rSV02 (central venous samples) are traditionally drawn from the PA catheter which includes all of the blood in the superior vena cava, that estimates the percentage of oxygen that is bound to hemoglobin - the amount of oxygen "left over" after the tissues get rid of what they need.
    \rThe results let us know whether cardiac output and oxygenation are adequate for the patient. If SV02 is decreased, then tissues are extracting a higher percentage of oxygen from the arterial blood, and the CO is not high enough to meet normal 02 demands.
    \rHigh SV02 in the presence of high lactate is inappropriate, which is suggestive of inadequate tissue perfusion. In the absence of a PA catheter, samples can be taken from the IJ or subclavian and interpreted the same.
    """
    
    case CentralVenousPressure = """
    \rCentral Venous Pressure is an estimated measurement of blood pressure reflecting pressure in the superior vena cava and right atrium. These pressures are used to assess right ventricular preload – and to a lesser extent, left ventricular preload.
    \rDepending on the volume status, these pressures can change.  Changes in CVP do not directly reflect cardiac output.  Pressure changes should be jointly analyzed with cardiac output to determine the patient's fluid status.
    \rFor example, a high CVP with low cardiac output would indicate that the fluid response is minimal. Conversely, an increase in cardiac output after fluid bolus would indicate the patient is fluid responsive.
    \rThere are 5 points of reference on the waveform: A, C, X, V and V.
    \rA wave: End of diastole: Represents the rise in atrial pressure and atrial contraction.
    \rC wave: Early systole: Represents buldging of the tricuspid valve into the right atrium
    \rX descent: Mild systole: Pressure of the right atrium decreases. Downward movement of the tricuspid valve transitions into the right ventricle. Atrium relaxes.
    \rV wave: Tricuspid valve is close. This represents the peak atrial pressure during ventricular systole.
    \rY descent: Early diastole: Ventricular refilling occurs. The tricuspid valve opens early.
    """
    case RightVentricularPressure = """
    \rRight ventricular pressure is the pressure generated by the RV when the heart pumps blood through the pulmonary artery to the lungs.
    \rWhen the RV contracts, there's trivial tricuspid regurgitation. This measured velocity across the tricuspid valve is equal to the RV pressure.
    \rThis pressure can "estimate" the PA pressure, but is not an indicator of pulmonary hypertension in itself.
    \rCauses of increased RV pressure can include: pulmonary hypertension, heart failure, aortic stenosis, mitral regurgitation, PE, sleep apnea, lupus, pulmonary disease.
    """
    case PulmonaryArteryPressure = """
    \rPulmonary artery pressure measures pressure in the pulmonary artery. PA pressure is mainly to monitor for pulmonary hypertension, and may be beneficial in those patients who are in shock.
    \rThe use of the pulmonary artery catheter has significantly decreased over the years and has not been associated with improved patient outcomes.
    \rThe PA catheter alone is not accurate in identifying those patients who are floor responsive in the state of shock.
    """
    case PulmonaryArteryWedgePressure = """
    \rPulmonary artery wedge pressure or pulmonary artery occlusion pressure is the pressure measured when the pulmonary artery is occluded (wedged) in  one of the small branches of the pulmonary artery.
    \rA small amount of blood between the tip of the catheter and the left atrium is measured.
    \rIt is used to measure Left Ventricular End Diastolic Pressure (LVEDP). High wedge pressures indicate left ventricular failure, congestive heart failure, cardiac insufficiency, or mitral valve disease.
    """
    case CardiacOutput = """
    Cardiac output = stroke volume x heart rate.  This is the volume of blood that the heart pumps each minute. CO predicts the delivery of oxygen to the cells and can vary at any time based on the body's metabolic needs.
    \rFor example, a stroke volume of 80 mL per contraction at a heart rate of 70 bpm will be 5,600 ML's permitted (or 5.6 L per minute).
    """
    case CardiacIndex = """
    \rCardiac index (CI) is CO / BSA. Not to be confused with cardiac output, CI assesses the cardiac output based solely on the patient's size.
    \rHere, we can calculate the cardiac index by dividing the cardiac output by the person's body surface area.
    \rThe cardiac index measurement alone doesn't provide enough information to make a rational clinical decision.
    \rBoth factors cardiac output and cardiac index are essential to assess how well the heart is pumping and assess the effectiveness of  vasoactive and inotropic agents.
    """
    case StrokeVolume = """
    \rStroke volume is regulated by three factors 1. Preload, 2. Contractility, and 3. Afterload. Stroke volume determines the amount of blood (in mL's) that is ejected from the left ventricle for each beat.
    \rAny changes that affect the end diastolic/systolic Volumes will affect the SV. Changes in the heart rate alone will also affect the stroke volume.
    """
    case StrokeVolumeVariation = """
    \rStroke volume variation is measured to test fluid responsiveness when CVP is not available or reliable. It measures the change is stroke volume after mechanical ventilation, which will either increase or decrease venous return. SVV is the difference in the amount of blood ejected from the left ventricle in the aorta for each beat. Usually, when we breathe the blood pressure decreases slightly during inspiration, and this is known as with Pulsus Paradoxus.
    \rHowever, during intubation, positive pressure is exerted on the arteries which cause a reverse with Pulsus Paradoxus, where the pressure is increased. The literature cites continuous SVV monitoring optimal for fluid responsiveness.
    """
    case SystemicVascularResistance = """
    SVR is reflected when there are changes in the arterioles which affect left ventricular emptying.  SVR increases when there is peripheral vascular vasoconstriction- which ultimately increases stroke volume and cardiac output.
    \rConversely, a decrease in SVR (vasodilation)  or relaxation of the blood vessels causes the left ventricle to pump more efficiently because it does not need to pump more forcefully to open the aortic valve.
    \rUsually an increased SVR requires the use of vasodilators such as Nipride or diuretics if preload is elevated.
    \rThose with a low SVR may be treated with vasoactive agents such as norepinephrine, dopamine or fluids to treat hypotension.
    """
    case SystemicVascularResistanceIndex = """
    SVRI represents the resistance that the heart has to pump against. This is  simply afterload.  in the event that afterload is increased, the heart has to pump more forcefully to eject the same amount of blood as before.
    \rThe higher the afterload, the less cardiac output and the lower the afterload, the higher the cardiac output. If the afterload exceeds myocardial performance, then the heart will decompensate.
    """
    // case PulmonaryVascularResistance = ""
}
